// Mocks generated by Mockito 5.4.5 from annotations
// in test_app/test/providers/user_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_app/architecture/domain/entities/user_entity.dart' as _i5;
import 'package:test_app/architecture/domain/usecases/get_users_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUsersUseCase extends _i1.Mock implements _i3.GetUsersUseCase {
  MockGetUsersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<String, List<_i5.UserEntity>>> execute(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<_i2.Either<String, List<_i5.UserEntity>>>.value(
            _FakeEither_0<String, List<_i5.UserEntity>>(
          this,
          Invocation.method(
            #execute,
            [],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i4.Future<_i2.Either<String, List<_i5.UserEntity>>>);

  @override
  _i4.Future<_i2.Either<String, _i5.UserEntity?>> getUserById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<String, _i5.UserEntity?>>.value(
            _FakeEither_0<String, _i5.UserEntity?>(
          this,
          Invocation.method(
            #getUserById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<String, _i5.UserEntity?>>);

  @override
  _i4.Future<_i2.Either<String, List<_i5.UserEntity>>> searchUsers(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i4.Future<_i2.Either<String, List<_i5.UserEntity>>>.value(
            _FakeEither_0<String, List<_i5.UserEntity>>(
          this,
          Invocation.method(
            #searchUsers,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<String, List<_i5.UserEntity>>>);

  @override
  _i4.Future<_i2.Either<String, bool>> syncUsers() => (super.noSuchMethod(
        Invocation.method(
          #syncUsers,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<String, bool>>.value(
            _FakeEither_0<String, bool>(
          this,
          Invocation.method(
            #syncUsers,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<String, bool>>);

  @override
  _i4.Future<_i2.Either<String, bool>> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<String, bool>>.value(
            _FakeEither_0<String, bool>(
          this,
          Invocation.method(
            #clearCache,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<String, bool>>);

  @override
  _i4.Future<void> clearAndRefresh() => (super.noSuchMethod(
        Invocation.method(
          #clearAndRefresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
